# ---------- Stage 1 : Builder ----------
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

# ---------- Stage 2 : Runtime ----------
FROM node:20-alpine AS runtime
WORKDIR /app

COPY --from=builder /app/package*.json ./

# 👇 important fix here
RUN npm ci --omit=dev --legacy-peer-deps

COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["node", "dist/src/main.js"]