export const blogList = [
  {
    id: 1,
    title: "7 CSS tools you should be using",
    category: "development",
    subCategory: ["frontend", "ui/ux", "design"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    authorName: "Alice Johnson",
    authorAvatar: "/assets/images/authors/alice.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/designer-1.jpg",
    defaultDataflag: true,
  },
  {
    id: 2,
    title: "Milan Places That Highlight The City",
    category: "travel",
    subCategory: ["vacation", "holidays", "sight seeing"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    authorName: "Lorenzo Rossi",
    authorAvatar: "/assets/images/authors/lorenzo.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg",
    defaultDataflag: true,
  },
  {
    id: 3,
    title: "Online Shopping – An Alternative to Shopping in the Mall",
    category: "shopping",
    subCategory: ["e-commerce store", "clothing", "shopping store"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    authorName: "Maya Patel",
    authorAvatar: "/assets/images/authors/maya.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/fQwuyKJ9qxjSbr6REcgtmW-1200-80.jpg",
    defaultDataflag: true,
  },
  {
    id: 4,
    title: "ADVENTURE IN YOU",
    category: "adventure",
    subCategory: ["adrenaline", "stay-fit", "lifestyle"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    authorName: "Ethan Campbell",
    authorAvatar: "/assets/images/authors/ethan.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/graphic-design-trends.png",
    defaultDataflag: true,
  },
  {
    id: 5,
    title: "Loaded BBQ Baked Potatoes",
    category: "cooking",
    subCategory: ["bbq", "food", "lifestyle"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    authorName: "Sophie Nguyen",
    authorAvatar: "/assets/images/authors/sophie.jpg",
    createdAt: "June 03, 2021",
    cover: "/assets/images/make-it-personal.jpg",
    defaultDataflag: true,
  },
  {
    id: 6,
    title: "Beyond the Beach",
    category: "travel",
    subCategory: ["beaches", "sea", "holidays"],
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...",
    authorName: "Carlos Martinez",
    authorAvatar: "/assets/images/authors/carlos.jpg",
    createdAt: "June 03, 2021",
    cover:
      "/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg",
    defaultDataflag: true,
  },
];
